spring.application.name=DMS
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
spring.datasource.url=${DATABASE_CONNECTION_URL}
spring.datasource.username=${DATABASE_CONNECTION_USERNAME}
spring.datasource.password=${DATABASE_CONNECTION_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.jdbc.dialect=sql_server
#spring.data.jdbc.dialect=postgresql
server.port=${PORT:8008}
spring.jackson.serialization.fail-on-empty-beans=false
# keeps a transaction inside of the same entity manager until the web request is finished.
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.data.rest.base-path=/api
# Set the date format for JSON Output
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/New_York
# Turns off Spring Boot automatic exception handling
#server.error.whitelabel.enabled=false
#spring.web.resources.add-mappings=false
spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB
