package com.heftyb.dms.crm;

public enum JobTitle {
    SERVICE_WRITER, TECHNICIAN, SHOP_FOREMAN, LUBE_TECHNICIAN,
    SERVICE_MANAGER, PORTER, DETAILER, OFFICE_ADMIN, GREETER,
    SALES_MANAGER, GENERAL_MANAGER, FLOOR_MANAGER, SALES_DEPT, BDC,
    SOCIAL_MEDIA_MANAGER, OFFICE, PAYROLL_DEPT, FINANCE_MANAGER, FINANCE_DEPT,
    PARTS_MANAGER, PARTS_DEPT, PARTS_RUNNER, PARTS_DELIVERY, ACCOUNT_MANAGER,
    CUSTOMER_RETENTION, AFTER_SALES
}
